version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t myimage .
            docker tag myimage $DOCKER_REGISTRY/myimage:$CIRCLE_SHA1
            docker push $DOCKER_REGISTRY/myimage:$CIRCLE_SHA1